FROM ubuntu:12.04

RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y apache2 php5 php5-mysql php5-curl libapache2-mod-php5 

ENV APACHE_RUN_USER  www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR   /var/log/apache2

RUN rm -f /etc/apache2/sites-enabled/000-default.conf
ADD etc/000-default.conf /etc/apache2/sites-enabled/000-default.conf
ADD www /var/www

EXPOSE 80 

CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]
