# 
#    MySQL
#

FROM centos:centos6

RUN yum update -y
RUN yum install mysql-server.x86_64 -y
ADD sql /sql
RUN /etc/rc.d/init.d/mysqld start &&\
/usr/bin/mysql -u root -e 'create database sample' &&\
/usr/bin/mysql -u root -e "grant all privileges on *.* to root@'%' identified by 'password' with grant option" &&\
/usr/bin/mysql -u root -e 'show databases' &&\
/usr/bin/mysqladmin -u root password 'password' &&\
/usr/bin/mysql -u root --password=password sample </sql/bookstore0.sql &&\
/usr/bin/mysql -u root --password=password sample </sql/bookstore1.sql &&\
/usr/bin/mysql -u root --password=password sample </sql/bookstore2.sql &&\
/usr/bin/mysql -u root --password=password sample </sql/bookstore3.sql &&\
service mysqld stop


EXPOSE 3306

CMD ["/usr/bin/mysqld_safe"]
